In [1]:
import numpy as np

In [2]:
directory ="D:\\Chess\\dolphin_database\\"

In [8]:
A=np.load(directory+"D0.npz")
B=np.load(directory+"D1.npz")

xb=np.concatenate((A['arr_0'],B['arr_0']),axis=0)
xf=np.concatenate((A['arr_1'],B['arr_1']),axis=0)
y=np.concatenate((A['arr_2'],B['arr_2']),axis=0)
b=np.concatenate((A['arr_3'],B['arr_3']),axis=0)
t=np.concatenate((A['arr_4'],B['arr_4']),axis=0)



In [30]:
print(remaining_files)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
letter = "D"
trg_letter = "C"
remaining_files = list(range(1300))

while len(remaining_files)>0:
    A_idx  = np.random.choice(remaining_files)
    #print(A_idx)
    remaining_files.remove(A_idx)

    B_idx  = np.random.choice(remaining_files)
    #print(B_idx)
    remaining_files.remove(B_idx)


    A=np.load(directory+letter+str(A_idx)+".npz")
    B=np.load(directory+letter+str(B_idx)+".npz")

    xb=np.concatenate((A['arr_0'],B['arr_0']),axis=0)
    xf=np.concatenate((A['arr_1'],B['arr_1']),axis=0)
    y=np.concatenate((A['arr_2'],B['arr_2']),axis=0)
    b=np.concatenate((A['arr_3'],B['arr_3']),axis=0)
    t=np.concatenate((A['arr_4'],B['arr_4']),axis=0)

    c = list(zip(xb,xf,y,b,t))
    np.random.shuffle(c)
    xb,xf,y,b,t = zip(*c)


    np.savez_compressed(directory+trg_letter+str(A_idx)+'.npz',
                            xb[0:65536],
                            xf[0:65536],
                            y[0:65536],
                            b[0:65536],
                            t[0:65536])


    np.savez_compressed(directory+trg_letter+str(B_idx)+'.npz',
                            xb[65536:131072],
                            xf[65536:131072],
                            y[65536:131072],
                            b[65536:131072],
                            t[65536:131072])
    
    print("Made: "+trg_letter+str(A_idx)+'.npz')
    print("Made: "+trg_letter+str(B_idx)+'.npz')
    
    
letter = "C"
trg_letter = "B"
remaining_files = list(range(1300))

while len(remaining_files)>0:
    A_idx  = np.random.choice(remaining_files)
    #print(A_idx)
    remaining_files.remove(A_idx)

    B_idx  = np.random.choice(remaining_files)
    #print(B_idx)
    remaining_files.remove(B_idx)


    A=np.load(directory+letter+str(A_idx)+".npz")
    B=np.load(directory+letter+str(B_idx)+".npz")

    xb=np.concatenate((A['arr_0'],B['arr_0']),axis=0)
    xf=np.concatenate((A['arr_1'],B['arr_1']),axis=0)
    y=np.concatenate((A['arr_2'],B['arr_2']),axis=0)
    b=np.concatenate((A['arr_3'],B['arr_3']),axis=0)
    t=np.concatenate((A['arr_4'],B['arr_4']),axis=0)

    c = list(zip(xb,xf,y,b,t))
    np.random.shuffle(c)
    xb,xf,y,b,t = zip(*c)


    np.savez_compressed(directory+trg_letter+str(A_idx)+'.npz',
                            xb[0:65536],
                            xf[0:65536],
                            y[0:65536],
                            b[0:65536],
                            t[0:65536])


    np.savez_compressed(directory+trg_letter+str(B_idx)+'.npz',
                            xb[65536:131072],
                            xf[65536:131072],
                            y[65536:131072],
                            b[65536:131072],
                            t[65536:131072])
    
    print("Made: "+trg_letter+str(A_idx)+'.npz')
    print("Made: "+trg_letter+str(B_idx)+'.npz')
    

Made: C879.npz
Made: C349.npz
Made: C259.npz
Made: C1248.npz
Made: C1104.npz
Made: C795.npz
Made: C154.npz
Made: C653.npz
Made: C415.npz
Made: C497.npz
Made: C123.npz
Made: C830.npz
Made: C611.npz
Made: C554.npz
Made: C327.npz
Made: C782.npz
Made: C309.npz
Made: C1011.npz
Made: C912.npz
Made: C446.npz
Made: C864.npz
Made: C1175.npz
Made: C1167.npz
Made: C106.npz
Made: C952.npz
Made: C664.npz
Made: C47.npz
Made: C391.npz
Made: C332.npz
Made: C302.npz
Made: C441.npz
Made: C899.npz
Made: C577.npz
Made: C809.npz
Made: C955.npz
Made: C205.npz
Made: C699.npz
Made: C831.npz
Made: C494.npz
Made: C601.npz
Made: C949.npz
Made: C763.npz
Made: C643.npz
Made: C480.npz
Made: C301.npz
Made: C109.npz
Made: C642.npz
Made: C105.npz
Made: C183.npz
Made: C706.npz
Made: C719.npz
Made: C284.npz
Made: C308.npz
Made: C644.npz
Made: C807.npz
Made: C388.npz
Made: C711.npz
Made: C316.npz
Made: C1077.npz
Made: C402.npz
Made: C745.npz
Made: C524.npz
Made: C455.npz
Made: C204.npz
Made: C766.npz
Made: C826.npz
Made:

Made: C927.npz
Made: C322.npz
Made: C437.npz
Made: C1265.npz
Made: C929.npz
Made: C1261.npz
Made: C396.npz
Made: C572.npz
Made: C1050.npz
Made: C897.npz
Made: C188.npz
Made: C762.npz
Made: C491.npz
Made: C243.npz
Made: C36.npz
Made: C872.npz
Made: C1117.npz
Made: C1201.npz
Made: C63.npz
Made: C387.npz
Made: C299.npz
Made: C616.npz
Made: C784.npz
Made: C737.npz
Made: C821.npz
Made: C544.npz
Made: C816.npz
Made: C739.npz
Made: C975.npz
Made: C836.npz
Made: C182.npz
Made: C1139.npz
Made: C992.npz
Made: C679.npz
Made: C893.npz
Made: C1243.npz
Made: C456.npz
Made: C628.npz
Made: C1030.npz
Made: C385.npz
Made: C1245.npz
Made: C1095.npz
Made: C865.npz
Made: C504.npz
Made: C680.npz
Made: C1005.npz
Made: C440.npz
Made: C1212.npz
Made: C328.npz
Made: C656.npz
Made: C1076.npz
Made: C29.npz
Made: C289.npz
Made: C208.npz
Made: C193.npz
Made: C348.npz
Made: C649.npz
Made: C1164.npz
Made: C1287.npz
Made: C1294.npz
Made: C677.npz
Made: C531.npz
Made: C28.npz
Made: C334.npz
Made: C790.npz
Made: C1147.n

Made: C822.npz
Made: C613.npz
Made: C1025.npz
Made: C1138.npz
Made: C460.npz
Made: C128.npz
Made: C646.npz
Made: C1148.npz
Made: C1221.npz
Made: C1210.npz
Made: C1131.npz
Made: C1200.npz
Made: C180.npz
Made: C1096.npz
Made: C849.npz
Made: C764.npz
Made: C323.npz
Made: C1078.npz
Made: C1262.npz
Made: C1047.npz
Made: C304.npz
Made: C360.npz
Made: C1297.npz
Made: C457.npz
Made: C2.npz
Made: C1288.npz
Made: C667.npz
Made: C1113.npz
Made: C119.npz
Made: C526.npz
Made: C553.npz
Made: C588.npz
Made: C1208.npz
Made: C55.npz
Made: C584.npz
Made: C957.npz
Made: C482.npz
Made: C230.npz
Made: C417.npz
Made: C828.npz
Made: C54.npz
Made: C414.npz
Made: C103.npz
Made: C112.npz
Made: C779.npz
Made: C1136.npz
Made: C629.npz
Made: C1068.npz
Made: C702.npz
Made: C1108.npz
Made: C1169.npz
Made: C760.npz
Made: C625.npz
Made: C748.npz
Made: C552.npz
Made: C842.npz
Made: C682.npz
Made: C453.npz
Made: C862.npz
Made: C144.npz
Made: C1105.npz
Made: C148.npz
Made: C1007.npz
Made: C787.npz
Made: C813.npz
Made: C1

Made: B749.npz
Made: B87.npz
70
1292
Made: B70.npz
Made: B1292.npz
254
382
Made: B254.npz
Made: B382.npz
1062
1280
Made: B1062.npz
Made: B1280.npz
890
676
Made: B890.npz
Made: B676.npz
539
7
Made: B539.npz
Made: B7.npz
448
595
Made: B448.npz
Made: B595.npz
1100
248
Made: B1100.npz
Made: B248.npz
488
903
Made: B488.npz
Made: B903.npz
268
491
Made: B268.npz
Made: B491.npz
626
333
Made: B626.npz
Made: B333.npz
719
49
Made: B719.npz
Made: B49.npz
1236
738
Made: B1236.npz
Made: B738.npz
1140
1053
Made: B1140.npz
Made: B1053.npz
1057
710
Made: B1057.npz
Made: B710.npz
1152
802
Made: B1152.npz
Made: B802.npz
1170
775
Made: B1170.npz
Made: B775.npz
823
849
Made: B823.npz
Made: B849.npz
1108
813
Made: B1108.npz
Made: B813.npz
884
1129
Made: B884.npz
Made: B1129.npz
163
918
Made: B163.npz
Made: B918.npz
552
882
Made: B552.npz
Made: B882.npz
365
45
Made: B365.npz
Made: B45.npz
349
1154
Made: B349.npz
Made: B1154.npz
165
590
Made: B165.npz
Made: B590.npz
594
1225
Made: B594.npz
Made: B1225.npz
265

Made: B322.npz
Made: B970.npz
951
599
Made: B951.npz
Made: B599.npz
660
691
Made: B660.npz
Made: B691.npz
77
205
Made: B77.npz
Made: B205.npz
795
78
Made: B795.npz
Made: B78.npz
803
690
Made: B803.npz
Made: B690.npz
543
1086
Made: B543.npz
Made: B1086.npz
664
185
Made: B664.npz
Made: B185.npz
134
388
Made: B134.npz
Made: B388.npz
279
702
Made: B279.npz
Made: B702.npz
166
1153
Made: B166.npz
Made: B1153.npz
176
1035
Made: B176.npz
Made: B1035.npz
1113
885
Made: B1113.npz
Made: B885.npz
619
1141
Made: B619.npz
Made: B1141.npz
530
609
Made: B530.npz
Made: B609.npz
505
503
Made: B505.npz
Made: B503.npz
401
1283
Made: B401.npz
Made: B1283.npz
948
753
Made: B948.npz
Made: B753.npz
798
1008
Made: B798.npz
Made: B1008.npz
857
150
Made: B857.npz
Made: B150.npz
808
1094
Made: B808.npz
Made: B1094.npz
292
280
Made: B292.npz
Made: B280.npz
627
1285
Made: B627.npz
Made: B1285.npz
381
1224
Made: B381.npz
Made: B1224.npz
731
282
Made: B731.npz
Made: B282.npz
323
902
Made: B323.npz
Made: B902.npz
1229

Made: B1201.npz
Made: B383.npz
629
881
Made: B629.npz
Made: B881.npz
110
647
Made: B110.npz
Made: B647.npz
785
711
Made: B785.npz
Made: B711.npz
1216
472
Made: B1216.npz
Made: B472.npz
1121
442
Made: B1121.npz
Made: B442.npz
792
581
Made: B792.npz
Made: B581.npz
1205
452
Made: B1205.npz
Made: B452.npz
891
475
Made: B891.npz
Made: B475.npz
161
1076
Made: B161.npz
Made: B1076.npz
960
989
Made: B960.npz
Made: B989.npz
474
747
Made: B474.npz
Made: B747.npz
861
536
Made: B861.npz
Made: B536.npz
182
1261
Made: B182.npz
Made: B1261.npz
1011
829
Made: B1011.npz
Made: B829.npz
636
1177
Made: B636.npz
Made: B1177.npz
421
678
Made: B421.npz
Made: B678.npz
964
65
Made: B964.npz
Made: B65.npz
943
523
Made: B943.npz
Made: B523.npz
3
355
Made: B3.npz
Made: B355.npz
1299
631
Made: B1299.npz
Made: B631.npz
1231
386
Made: B1231.npz
Made: B386.npz
58
852
Made: B58.npz
Made: B852.npz
735
961
Made: B735.npz
Made: B961.npz
877
1227
Made: B877.npz
Made: B1227.npz
1093
180
Made: B1093.npz
Made: B180.npz
1247


In [4]:
letter = "B"
trg_letter = "A"
remaining_files = list(range(1300))

while len(remaining_files)>0:
    A_idx  = np.random.choice(remaining_files)
    remaining_files.remove(A_idx)

    B_idx  = np.random.choice(remaining_files)
    remaining_files.remove(B_idx)


    A=np.load(directory+letter+str(A_idx)+".npz")
    B=np.load(directory+letter+str(B_idx)+".npz")

    xb=np.concatenate((A['arr_0'],B['arr_0']),axis=0)
    xf=np.concatenate((A['arr_1'],B['arr_1']),axis=0)
    y=np.concatenate((A['arr_2'],B['arr_2']),axis=0)
    b=np.concatenate((A['arr_3'],B['arr_3']),axis=0)
    t=np.concatenate((A['arr_4'],B['arr_4']),axis=0)

    c = list(zip(xb,xf,y,b,t))
    np.random.shuffle(c)
    xb,xf,y,b,t = zip(*c)


    np.savez_compressed(directory+trg_letter+str(A_idx)+'.npz',
                            xb[0:65536],
                            xf[0:65536],
                            y[0:65536],
                            b[0:65536],
                            t[0:65536])


    np.savez_compressed(directory+trg_letter+str(B_idx)+'.npz',
                            xb[65536:131072],
                            xf[65536:131072],
                            y[65536:131072],
                            b[65536:131072],
                            t[65536:131072])
    
    print("Made: "+trg_letter+str(A_idx)+'.npz')
    print("Made: "+trg_letter+str(B_idx)+'.npz')
    

Made: A518.npz
Made: A896.npz
Made: A846.npz
Made: A199.npz
Made: A110.npz
Made: A977.npz
Made: A252.npz
Made: A908.npz
Made: A871.npz
Made: A498.npz
Made: A1103.npz
Made: A667.npz
Made: A170.npz
Made: A1106.npz
Made: A276.npz
Made: A1094.npz
Made: A851.npz
Made: A603.npz
Made: A357.npz
Made: A521.npz
Made: A514.npz
Made: A140.npz
Made: A219.npz
Made: A65.npz
Made: A798.npz
Made: A106.npz
Made: A695.npz
Made: A1165.npz
Made: A345.npz
Made: A856.npz
Made: A623.npz
Made: A1000.npz
Made: A1228.npz
Made: A873.npz
Made: A27.npz
Made: A685.npz
Made: A1070.npz
Made: A1005.npz
Made: A325.npz
Made: A289.npz
Made: A183.npz
Made: A433.npz
Made: A404.npz
Made: A820.npz
Made: A255.npz
Made: A859.npz
Made: A626.npz
Made: A723.npz
Made: A92.npz
Made: A415.npz
Made: A75.npz
Made: A308.npz
Made: A1150.npz
Made: A986.npz
Made: A818.npz
Made: A10.npz
Made: A301.npz
Made: A565.npz
Made: A225.npz
Made: A632.npz
Made: A234.npz
Made: A882.npz
Made: A1140.npz
Made: A103.npz
Made: A2.npz
Made: A285.npz
Made: A

Made: A1071.npz
Made: A212.npz
Made: A939.npz
Made: A857.npz
Made: A1114.npz
Made: A384.npz
Made: A394.npz
Made: A701.npz
Made: A211.npz
Made: A1127.npz
Made: A600.npz
Made: A327.npz
Made: A1268.npz
Made: A635.npz
Made: A674.npz
Made: A828.npz
Made: A235.npz
Made: A847.npz
Made: A810.npz
Made: A719.npz
Made: A840.npz
Made: A472.npz
Made: A552.npz
Made: A929.npz
Made: A808.npz
Made: A1198.npz
Made: A341.npz
Made: A920.npz
Made: A511.npz
Made: A960.npz
Made: A1259.npz
Made: A696.npz
Made: A766.npz
Made: A1278.npz
Made: A699.npz
Made: A512.npz
Made: A1069.npz
Made: A1013.npz
Made: A1091.npz
Made: A122.npz
Made: A1093.npz
Made: A220.npz
Made: A1049.npz
Made: A500.npz
Made: A760.npz
Made: A1010.npz
Made: A124.npz
Made: A594.npz
Made: A816.npz
Made: A264.npz
Made: A1171.npz
Made: A367.npz
Made: A1047.npz
Made: A67.npz
Made: A380.npz
Made: A1038.npz
Made: A1289.npz
Made: A1222.npz
Made: A731.npz
Made: A1290.npz
Made: A295.npz
Made: A1229.npz
Made: A226.npz
Made: A1163.npz
Made: A477.npz
Made:

Made: A1054.npz
Made: A26.npz
Made: A880.npz
Made: A1116.npz
Made: A1130.npz
Made: A1073.npz
Made: A779.npz
Made: A1036.npz
Made: A1203.npz
Made: A359.npz
Made: A1254.npz
Made: A742.npz
Made: A1099.npz
Made: A89.npz
Made: A1155.npz
Made: A801.npz
Made: A1235.npz
Made: A994.npz
Made: A721.npz
Made: A663.npz
Made: A572.npz
Made: A617.npz
Made: A1269.npz
Made: A627.npz
Made: A249.npz
Made: A570.npz
Made: A40.npz
Made: A489.npz
Made: A1182.npz
Made: A998.npz
Made: A397.npz
Made: A1170.npz
Made: A431.npz
Made: A231.npz
Made: A90.npz
Made: A486.npz
Made: A949.npz
Made: A545.npz
Made: A850.npz
Made: A286.npz
Made: A421.npz
Made: A267.npz
Made: A507.npz
Made: A1011.npz
Made: A502.npz
Made: A28.npz
Made: A1029.npz
Made: A306.npz
Made: A835.npz
Made: A215.npz
Made: A460.npz
Made: A66.npz
Made: A633.npz
Made: A392.npz
Made: A12.npz
Made: A573.npz
Made: A988.npz
Made: A902.npz
Made: A101.npz
Made: A834.npz
Made: A679.npz
Made: A958.npz
Made: A684.npz
Made: A51.npz
Made: A458.npz
Made: A84.npz
Made

In [5]:
letter = "A"
trg_letter = "E"
remaining_files = list(range(1300))

while len(remaining_files)>0:
    A_idx  = np.random.choice(remaining_files)
    remaining_files.remove(A_idx)

    B_idx  = np.random.choice(remaining_files)
    remaining_files.remove(B_idx)


    A=np.load(directory+letter+str(A_idx)+".npz")
    B=np.load(directory+letter+str(B_idx)+".npz")

    xb=np.concatenate((A['arr_0'],B['arr_0']),axis=0)
    xf=np.concatenate((A['arr_1'],B['arr_1']),axis=0)
    y=np.concatenate((A['arr_2'],B['arr_2']),axis=0)
    b=np.concatenate((A['arr_3'],B['arr_3']),axis=0)
    t=np.concatenate((A['arr_4'],B['arr_4']),axis=0)

    c = list(zip(xb,xf,y,b,t))
    np.random.shuffle(c)
    xb,xf,y,b,t = zip(*c)


    np.savez_compressed(directory+trg_letter+str(A_idx)+'.npz',
                            xb[0:65536],
                            xf[0:65536],
                            y[0:65536],
                            b[0:65536],
                            t[0:65536])


    np.savez_compressed(directory+trg_letter+str(B_idx)+'.npz',
                            xb[65536:131072],
                            xf[65536:131072],
                            y[65536:131072],
                            b[65536:131072],
                            t[65536:131072])
    
    print("Made: "+trg_letter+str(A_idx)+'.npz')
    print("Made: "+trg_letter+str(B_idx)+'.npz')
    

Made: E1225.npz
Made: E597.npz
Made: E1228.npz
Made: E1261.npz
Made: E350.npz
Made: E546.npz
Made: E819.npz
Made: E310.npz
Made: E229.npz
Made: E23.npz
Made: E1015.npz
Made: E653.npz
Made: E716.npz
Made: E254.npz
Made: E1255.npz
Made: E888.npz
Made: E377.npz
Made: E813.npz
Made: E1198.npz
Made: E1283.npz
Made: E394.npz
Made: E256.npz
Made: E681.npz
Made: E820.npz
Made: E1287.npz
Made: E726.npz
Made: E1133.npz
Made: E307.npz
Made: E591.npz
Made: E264.npz
Made: E954.npz
Made: E929.npz
Made: E312.npz
Made: E972.npz
Made: E408.npz
Made: E222.npz
Made: E85.npz
Made: E561.npz
Made: E186.npz
Made: E850.npz
Made: E1245.npz
Made: E1157.npz
Made: E1094.npz
Made: E918.npz
Made: E883.npz
Made: E757.npz
Made: E914.npz
Made: E61.npz
Made: E601.npz
Made: E1163.npz
Made: E1138.npz
Made: E174.npz
Made: E1014.npz
Made: E1085.npz
Made: E924.npz
Made: E655.npz
Made: E941.npz
Made: E935.npz
Made: E299.npz
Made: E1056.npz
Made: E577.npz
Made: E1169.npz
Made: E1242.npz
Made: E1267.npz
Made: E656.npz
Made: E1

Made: E1147.npz
Made: E5.npz
Made: E314.npz
Made: E1205.npz
Made: E57.npz
Made: E595.npz
Made: E1168.npz
Made: E687.npz
Made: E266.npz
Made: E194.npz
Made: E1149.npz
Made: E213.npz
Made: E1050.npz
Made: E1048.npz
Made: E1128.npz
Made: E718.npz
Made: E578.npz
Made: E46.npz
Made: E1035.npz
Made: E661.npz
Made: E214.npz
Made: E756.npz
Made: E620.npz
Made: E258.npz
Made: E640.npz
Made: E311.npz
Made: E145.npz
Made: E372.npz
Made: E432.npz
Made: E1076.npz
Made: E218.npz
Made: E418.npz
Made: E158.npz
Made: E1006.npz
Made: E575.npz
Made: E1102.npz
Made: E777.npz
Made: E584.npz
Made: E523.npz
Made: E111.npz
Made: E48.npz
Made: E141.npz
Made: E1.npz
Made: E927.npz
Made: E908.npz
Made: E658.npz
Made: E354.npz
Made: E1288.npz
Made: E252.npz
Made: E176.npz
Made: E1036.npz
Made: E986.npz
Made: E15.npz
Made: E430.npz
Made: E878.npz
Made: E1077.npz
Made: E238.npz
Made: E799.npz
Made: E386.npz
Made: E1189.npz
Made: E964.npz
Made: E975.npz
Made: E752.npz
Made: E452.npz
Made: E1030.npz
Made: E495.npz
Ma

Made: E165.npz
Made: E642.npz
Made: E1178.npz
Made: E500.npz
Made: E444.npz
Made: E473.npz
Made: E1220.npz
Made: E641.npz
Made: E840.npz
Made: E277.npz
Made: E1202.npz
Made: E958.npz
Made: E159.npz
Made: E779.npz
Made: E535.npz
Made: E512.npz
Made: E124.npz
Made: E868.npz
Made: E1159.npz
Made: E534.npz
Made: E785.npz
Made: E874.npz
Made: E246.npz
Made: E1127.npz
Made: E405.npz
Made: E748.npz
Made: E121.npz
Made: E903.npz
Made: E1057.npz
Made: E541.npz
Made: E1276.npz
Made: E152.npz
Made: E581.npz
Made: E1037.npz
Made: E1272.npz
Made: E568.npz
Made: E1087.npz
Made: E1011.npz
Made: E424.npz
Made: E766.npz
Made: E232.npz
Made: E114.npz
Made: E701.npz
Made: E78.npz
Made: E514.npz
Made: E453.npz
Made: E711.npz
Made: E715.npz
Made: E1278.npz
Made: E1275.npz
Made: E462.npz
Made: E1062.npz
Made: E671.npz
Made: E905.npz
Made: E298.npz
Made: E1145.npz
Made: E347.npz
Made: E1044.npz
Made: E906.npz
Made: E163.npz
Made: E837.npz
Made: E947.npz
Made: E699.npz
Made: E208.npz
Made: E391.npz
Made: E34.

In [35]:
xb.shape

(131072, 8, 8, 72)

In [ ]:
c = list(zip(x_bool_train, x_float_train, ytrain, btrain, timetaken))
random.shuffle(c)
x_bool_train, x_float_train, ytrain, btrain, timetaken, boards = zip(*c)

In [44]:
v = np.arange(36).reshape((6,3,2))
z = np.arange(36).reshape((6,3,2))
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [39]:
z.shape

(6, 3, 2)

In [40]:
z[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
np.random.shuffle(z)

In [46]:
z

array([[[24, 25],
        [26, 27],
        [28, 29]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[30, 31],
        [32, 33],
        [34, 35]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [48]:
c = list(zip(v,z))
np.random.shuffle(c)
v1,z1 = zip(*c)

In [49]:
v1

(array([[ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[24, 25],
        [26, 27],
        [28, 29]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[30, 31],
        [32, 33],
        [34, 35]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[18, 19],
        [20, 21],
        [22, 23]]))

In [50]:
z1

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[30, 31],
        [32, 33],
        [34, 35]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[24, 25],
        [26, 27],
        [28, 29]]),
 array([[18, 19],
        [20, 21],
        [22, 23]]))

In [ ]:
 np.savez_compressed('.npz',
                        xb[0:65536],
                        xf[0:65536],
                        y[0:65536],
                        b[0:65536],
                        t[0:65536])
    
    
np.savez_compressed('.npz',
                        xb[65536:131072],
                        xf[65536:131072],
                        y[65536:131072],
                        b[65536:131072],
                        t[65536:131072])

In [32]:
xb[0:10].shape

(10, 8, 8, 72)

In [9]:
print(xb.shape)

(131072, 8, 8, 72)


In [ ]:
l = ["A","B","C"]